//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2,3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
package br.com.henrique.projecteuler;

public class FibonacciPair {
  public void execute(){
    int sum = 0;
    int a = 1;
    int b = 2;

    while(b < 4000000){
      if(b % 2 == 0){
        sum += b;
      }
      int next = a + b;
      a = b;
      b = next;
    }
    System.out.println(sum);
  }
}
